Do explicit cast from size_t to jsize.
Summary:
Implicit cast causes build error on M1 laptop:
```
error: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'jsize' (aka 'int') [-Werror,-Wshorten-64-to-32]
  auto rawElement = env->GetObjectArrayElement(this->self(), idx);
```

Reviewed By: mhorowitz

Differential Revision: D38791257

fbshipit-source-id: a17df571cbe0486ca336f29174f8c19e70831386